### ISSUE TITLE
NPC skipping issue

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TSAPI#101]
In the interim waiting for Orion to cook, we need to look into https://github.com/NyxStudios/TShock/issues/1231, but this is a vanilla issue according to @ProfessorXZ which means it will regress if fixed here in Orion.

**Comment by QuiCM** [comment]
Vanilla issues are, for the most part, left to vanilla. I'm not sure we can do much about this without rewriting the network protocol.
