### ISSUE TITLE
Add "Pull Request Wanted" label

### ISSUE THREAD

**Issue by Simon311** [Pryaxis/TSAPI#104]
I would love to see "Pull Request Wanted" label added to issues on this repo.

**Comment by Ijwu** [comment]
I've begun using the `help wanted` tag. If we prefer the `Pull Request Wanted` label then we can replace the text under `help wanted` with `Pull Request Wanted`.

**Comment by hakusaro** [comment]
@Simon311 got you, will do when I get home, before I go to sleep, but after I make some tea

**Comment by hakusaro** [comment]
Done.
