### ISSUE TITLE
Sand Sharks and their biome relatives skip a lot, even on localhost

### ISSUE THREAD

**Issue by Kojirremer** [Pryaxis/TSAPI#110]
Just what the tin says. Pretty much every mob, worm enemies included, work as intended on localhost. However, sand sharks will skip quite a bit when hit for no apparent reason.
On a remote install one would think it's just lag, but it even happens on localhost, where even the biggest worms don't skip when hit.

Tested on TShock 4.3.20, clean install (just in case).

**Comment by DaBomberNTG** [comment]
Replicated this on local, my sand sharks would disappear when hit and would reappear in 5-15 secs later.

**Comment by Kojirremer** [comment]
This is still a thing on latest unstable (1371).

**Comment by Kojirremer** [comment]
Closing since it appears to have been fixed for quite a while (sorry, I forgot this existed).
