### ISSUE TITLE
API crashes on startup on Chinese language systems?

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TSAPI#111]
I'm not entirely sure about the root cause here, but a user reported having issues with the API starting on Chinese, English systems.

[ServerLog.txt](https://github.com/NyxStudios/TerrariaAPI-Server/files/563331/ServerLog.txt)
[ServerLog (1).txt](https://github.com/NyxStudios/TerrariaAPI-Server/files/563332/ServerLog.1.txt)

It wasn't TShock related, and it wasn't file permissions related, I assume some weird quirk about how either we're compiling TSAPI or how the decompile works is causing this. He said TShock 4.0 started fine, and also said the normal server starts fine. Without TShock, it crashes, and with it, it crashes.

**Comment by mistzzt** [comment]
It was not related to the system language.

The exception was occurred when TSAPI tried to load the `Last Used Time`.
The user must used an **older version of TSAPI** while **maps of newer version** existed.
I have reproduced this situation as I said above, using older version of TSAPI and maps of newer version.

But the vanilla server seems to skip maps with newer version on startup.

**Comment by grapeszy** [comment]
Yes, I've tried the TSv4.0. 
A solution for this is: Delete the old world map files.

**Comment by hakusaro** [comment]
We really need a solution for the world file problems. This is getting annoying.

**Comment by tylerjwatson** [comment]
Can we make a concrete repro scenario?  Maybe provide some world files affected by these sorts of bugs?

At the very least it's trivial to handle errors loading world files.

**Comment by QuiCM** [comment]
No further issues in over a year, closing.

**Comment by hakusaro** [comment]
@QuiCM mist would have noticed this.
