### ISSUE TITLE
 NPC's they are not spawning

### ISSUE THREAD

**Issue by dark22** [Pryaxis/TSAPI#118]
@Zaicon, I know that the current build for the update is not yet final, but I would like to report that NPC's are not auto spawning, sometimes it is possible to see a Devourer in map, the command /sm (Example: /sm zombie 50), also does not work. Some boss and events are working perfectly, both through commands or over items.

Thank you very much for the excellent work in updating!

**Comment by QuiCM** [comment]
Confirmed, some 'boss' monsters such as the Wyvern will spawn, but nothing else

**Comment by dark22** [comment]
The changes made to this pull #120 seems to work well, but Moon Lord, Lunatic Cultist, Lunatic Devotes and some other NPCs are not being invoked by command. Through items are summoned normally.

Although not connected with this update, but after this pull #106 the TowerNPCs are disappearing from the map for no apparent reason, to test just use AIO Plugin and invokes all TowerNPCs and wait for them to be removed randomly. This did not happen in any version of TShock previous to mencioned pull.

Thanks very much for the update!

**Comment by tlworks** [comment]
@dark22 This also counts for some other NPC's such as some OOA (Old One's Army) Monsters, Big Mimics and some NPC's spawned by the Lunatic Cultist. Not to forget that some types of Monsters simply cannot be spawned as they always remain the first ID in the list.

**Comment by QuiCM** [comment]
I believe this was prior to OTAPI integration. Closing.
