### ISSUE TITLE
Time Skipping is still a known issue.

### ISSUE THREAD

**Issue by tlworks-dev** [Pryaxis/TSAPI#124]
Apart from monster skipping, which simply is to be resolved by Re-Logic which probably will be buried deep down in the ground I'd like to share that Time Skipping is still a known issue in the latest OTAPI Pre-Release. It has improved quite a lot from TSAPI but it remains an issue which should be fixed if possible.

**Comment by ivanbiljan** [comment]
OTAPI is just an API for Terraria that exposes a lot of events for us. It does provide some optimisations (like with tiles) but I really don't think fixing ReLogic's code should be done by death because that's not how I see OTAPI. But that's just my opinion.

**Comment by QuiCM** [comment]
No reply from OP since 2015, closing. Please open a new issue if this is still occuring

**Comment by hakusaro** [comment]
Wow that's an old issue.
