### ISSUE TITLE
(#484+) World Saving fails at "Validating World Save 1%)

### ISSUE THREAD

**Issue by Marcus101RR** [Pryaxis/TSAPI#14]
Issue: When the world attempts to save, it will not finish saving nor create a backup world file. It remains hanging in console at Validating World Save 1%. Meanwhile, server can operate normally, however, if server is restarted, crashes, or closed, the world will be at its last successful save or use a later stable version of TerrariaServer.exe. As far as testing goes, this is not an issue with TShock DLL.

**Comment by QuiCM** [comment]
![screenshot](https://dl.dropboxusercontent.com/u/98954663/ShareX/2015/07/2015-07-17_12-33-38.png)

**Comment by Marcus101RR** [comment]
![](http://i.imgur.com/DXaemuv.jpg)

**Comment by QuiCM** [comment]
Was this present in previous builds?

**Comment by Marcus101RR** [comment]
No, Issue FIXED #488
