### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by hakusaro** [Pryaxis/TSAPI#165]
This repo no longer has the full decompile of the Terraria Server source code. Therefore, we should have our GPL v3 stamp on everything in this repo too (as we do for TShock).

That is, we just need to copy the `COPYING` file from TShock and put it here.

**Comment by sowelipililimute** [comment]
was done with https://github.com/Pryaxis/TSAPI/commit/752bc053371aa51bf008c5bcd54f3517b3f4136a
