### ISSUE TITLE
World stops loading for clients...

### ISSUE THREAD

**Issue by Marcus101RR** [Pryaxis/TSAPI#26]
The world stops loading after some time for all clients, only way to fix this is to restart the server and it will load for a while. Figured I put this issue up until it actually gets resolved in the future. So no one misses out on that fact that the issue exists or is too lazy to put it out there.
![](http://i.imgur.com/UCof7df.png)

**Comment by hakusaro** [comment]
cc @tylerjwatson

**Comment by hakusaro** [comment]
@Marcus101RR please provide a memory dump of the server executable during this condition and/or reproduction steps.

**Comment by Marcus101RR** [comment]
http://74.91.127.178:8080/FastDL/TerrariaServer.DMP
Memory dump of world stopped loading

**Comment by Marcus101RR** [comment]
Another World stopped loading tiles: http://74.91.127.178:8080/FastDL/TerrariaServer.zip
Joined as Slot 19, coordinates: 4201, 288

**Comment by tylerjwatson** [comment]
Links are invalid.

**Comment by Marcus101RR** [comment]
Try again, they work fine for me.
