### ISSUE TITLE
Lost Connection Repeatedly 5-10 minutes

### ISSUE THREAD

**Issue by Marcus101RR** [Pryaxis/TSAPI#30]
So, we keep losing connection now, cannot confirm or deny if the issue causes this: https://github.com/NyxStudios/TerrariaAPI-Server/commit/8e5d5931525ef0fc73362593106abbbf048c7f74

**Comment by hakusaro** [comment]
There's no actual information in this report to even remotely diagnose a problem.

**Comment by Marcus101RR** [comment]
There are no logs to show what happened either.

**Comment by Marcus101RR** [comment]
http://i.imgur.com/2A6tmPc.png

**Comment by tylerjwatson** [comment]
- no memory dump
- no tshock version
- no detailed explanation of the problem

closing until you learn how to report issues that aren't complete rubbish.
