### ISSUE TITLE
Repeated leaves and joins results in being stuck at "Found Server"

### ISSUE THREAD

**Issue by QuiCM** [Pryaxis/TSAPI#33]
Steps leading up to this issue:
- Created a new world (small, non-expert) via server console
- Opened world
- Joined and disconnected as fast as possible with one character, 7 times

After a not attempting to connect for ~10 seconds, I was once again able to connect, however quickly disconnecting and attempting to reconnect once again results in being stuck at "Found Server".

**Comment by QuiCM** [comment]
After getting stuck at "Found Server", I was successfully able to connect with a different character. After doing so I was unable to reproduce this issue without restarting the server

**Comment by tylerjwatson** [comment]
Is this locally?

**Comment by QuiCM** [comment]
Yes. Will test connecting to an external server

**Comment by tylerjwatson** [comment]
Locally is enough to reporoduce for now.  It's probably terraria trying to send packets to clients that aren't fully connected yet before the write thread has a chance to spawn.  

Will take a look asap

**Comment by QuiCM** [comment]
16 connections into external server connection, and cannot reproduce. The connection process is far slower than local, however, so it may be recovering before I attempt to reconnect
