### ISSUE TITLE
Building in Windows (Instead of Mono) causes traps to just not work

### ISSUE THREAD

**Issue by tysonstrange** [Pryaxis/TSAPI#43]
When you use VS To build in windows,  it will build but no traps will trigger.

Seems teleporters and shit still work though, so its not all mechanics.

**Comment by hakusaro** [comment]
That's very, very weird.

**Comment by QuiCM** [comment]
This issue has been around for a while. We never figured out the cause. Fortunately Travis builds with Mono

**Comment by tysonstrange** [comment]
Tell me about it....

Ask Tyler and see what he thinks about it... hahahahahahaha

**Comment by hakusaro** [comment]
@WhiteXZ *bamboo

**Comment by QuiCM** [comment]
Yeah, that

**Comment by tysonstrange** [comment]
Well, orion will probably take care of that, along with countless other issues.

not a big deal.

**Comment by gerardmistletoe** [comment]
It's not Windows specific. I build and run with Mono (xbuild) on Linux and traps don't work.

**Comment by Arrenton** [comment]
Same here. I tried to build in Mono using Linux and xbuild and it still doesn't work. I have tried Xamarin Studio as well in Windows to try and build Mono, with the same results.
Hopefully this does get fixed.

**Comment by hakusaro** [comment]
What version of Mono?

**Comment by Arrenton** [comment]
I would assume the latest since I used the install guide for linux on mono-project.com. (http://www.mono-project.com/docs/getting-started/install/linux/) But if you need me to check, I can.

EDIT: Linux is using Mono JIT Compiler version 4.2.1.102

**Comment by QuiCM** [comment]
Using Ubuntu 14.04 and Mono 4.0.5, traps work when the project is compiled with xbuild

**Comment by tylerjwatson** [comment]
> Linux is using Mono JIT Compiler version 4.2.1.102

Thanks.   This is important because it gives us something to look at, particularly the diffs between 4.2.1 and 4.0.5.  Now that the .NET CLR and the BCL is open source, mono have continuously been adopting MS implementations in lieu of their own in the interest of binary compatibility.  It could be something in these references that are causing this.

I still don't have anything concrete to go on, but its a start.

**Comment by Arrenton** [comment]
Compiling with Mono 4.0.5 worked! Thank you guys so much!

Here's to me hoping you guys can figure out what's going on here! Best of luck to you!

**Comment by tylerjwatson** [comment]
According to http://www.mono-project.com/docs/about-mono/releases/4.2.1/, it replaces some ~500 types with Microsoft's implementation.

This is going to be a pain.

**Comment by Arrenton** [comment]
I would like to note this also fixes Training Dummies, and invisible Bombs/Dynamite.
Although Campfires still seem to disappear when trying to disable them (right click.)

**Comment by tysonstrange** [comment]
Holy. Fucking. Shit.

Invis bombs are fixed? Gimme.

**Comment by hakusaro** [comment]
Hmm, the build server is on 4.0.2.0. Invisible bombs happen in the latest
official build?

**Comment by Arrenton** [comment]
Yes. And going to 4.0.5.1 fixed it for me.

**Comment by tysonstrange** [comment]
> Hmm, the build server is on 4.0.2.0. Invisible bombs happen in the latest
> official build?

Yeah, pretty sure its still an issue here

**Comment by Arrenton** [comment]
Okay, so the invisible bombs aren't 100% fixed but they're working almost 80% of the time now instead of never working at all.

**Comment by tysonstrange** [comment]
> Okay, so the invisible bombs aren't 100% fixed but they're working almost 80% of the time now instead of never working at all

Thats how it's always been...

It's never been so bad that they're invisible 100% of the time.

**Comment by tylerjwatson** [comment]
On my mono-4.2.1 instance, I am able to trigger a super dart trap with a lever once, and only once if the solution is compiled in release mode with `xbuild /p:Configuration=Release`.

**Comment by QuiCM** [comment]
I was able to trigger dart traps, spear traps, and flame traps continuously using a switch with a 4.2.1 instance

**Comment by tylerjwatson** [comment]
More info?  I should be able to trigger a super dart trap from a wire and a lever, right?  Doesn't have to be in a certain biome or at night?  Any other variables? Platform?  Did you compile it or run stock?

Mono-4.0 binaries from our CI has always worked.  This doesn't work when I compile the image using >= mono-4.0.2 or windows

**Comment by hakusaro** [comment]
👍👍👍😘😘😘
