### ISSUE TITLE
Joining with same name kicks the other

### ISSUE THREAD

**Issue by tysonstrange** [Pryaxis/TSAPI#44]
It used to be that if "Panther" was already online, trying to join with another player called "Panther" would be met with "Panther is already online", but now it kicks the player in game and lets this new player join.

I think its SendQ, as I noticed it around that time, but now people are catching on and causing problems.

**Comment by AxisKriel** [comment]
SendQ is long gone by now, and we haven't had reports of this occurring in quite a while. Re-open this if still an issue.
