### ISSUE TITLE
TEItemFrame doesn't load or send properly.

### ISSUE THREAD

**Issue by Pilihp64** [Pryaxis/TSAPI#50]
When TerrariaAPI-Server loads a world with a TEItemFrame, clients connected will not receive that "section" of the map, leaving a void.

Place an item in an Item frame in single player and save the world, load this world with a recent TerrariaAPI-Server and connect. The area with the TEItemFrame is now a void as it appears to the character.  This could be a loading problem, or a network sending problem leaving the section blank.

This happens regardless of any plugins including TShock.

**Comment by AxisKriel** [comment]
Does this work on vanilla TerrariaServer? Could be a bug on their end.

**Comment by Pilihp64** [comment]
Yes the normal server works as expected, it syncs properly and items can be placed and taken from Item frames.

Item frames themselves can be placed on TerrariaAPI, but you can't place anything inside the frame (nothing happens at all). So it makes sense that something is wrong with the entity responsible for that on the server.

**Comment by AxisKriel** [comment]
Please attempt to reproduce with the latest changes.

**Comment by Pilihp64** [comment]
No it still does not seem to function in any way, same symptoms.

**Comment by AndrioCelos** [comment]
I've seen the same issue with _all_ tile entities.

**Comment by Pilihp64** [comment]
I compared Entity functions with my personal decompile where Entities worked, found a loading mistake where they were never initialized.

**Comment by AxisKriel** [comment]
So is this fixed now? Let me know if I can close this issue.

**Comment by Pilihp64** [comment]
Yes, fixed as far as I've tested.
