### ISSUE TITLE
Pressure Plates don't seem to be working

### ISSUE THREAD

**Issue by recon88** [Pryaxis/TSAPI#56]
I just updated to the latest version and it seems like normal Pressure Plates are not working.
They are working fine on Vanilla.

**Comment by AxisKriel** [comment]
See #55.

**Comment by recon88** [comment]
Ah, was checking earlier and couldn't find a ticket about it :P

**Comment by AxisKriel** [comment]
Yeah, it's not visible under Issues because it's a Pull Request. If that's merged, this should be fixed.
