### ISSUE TITLE
Unable to generate world [1.3.2.1]

### ISSUE THREAD

**Issue by Patrikkk-zz** [Pryaxis/TSAPI#83]
Happens at 11%, Chiseling marble. 
![ss 2016-07-23 at 05 17 28](https://cloud.githubusercontent.com/assets/5616692/17078680/620b01fa-50f9-11e6-97f9-65d183be4c1d.png)

**Comment by ivanbiljan** [comment]
Can't confirm this particularly, but world creation seems to stop at 24%. This was tested on both the last (1.3.1.1) release and the current build. I've waited 5 minutes but nothing happened. Cannot guarantee it always happens, but it did happen the last 3-4 times I tried.

**Comment by Patrikkk-zz** [comment]
Idk how long it took. But now map generated :/ 
It's messing with me.

**Comment by hakusaro** [comment]
Not relevant post-Mintaka.
