### ISSUE TITLE
TSApi for Terraria 1.3.3.x Updated File List

### ISSUE THREAD

**Issue by QuiCM** [Pryaxis/TSAPI#94]
This issue should be updated as changes are added. Anything listed here should be considered **completed**.
If you have PRed a file or files, please tag me in a reply to this issue to have them added to the list.
- Projectile.cs
- GlowMaskID.cs
- Recipe.cs
- TileID.cs
- ProjectileID.cs
- ExtrasID.cs
- DustID.cs
- BuffID.cs
- NPCID.cs
- ItemID.cs
- ArmorID.cs
- Lang.cs
- MessageBuffer.cs
- TileObjectData.cs
- Sandstorm.cs
- NetMessage.cs
- FixEploitManEaters.cs    (seems like they made a typo in the file name here)
- Worldgen.cs
- NPC.cs
- MountID.cs
- GoreID.cs
- WorldFile.cs
- ISocket.cs
- TcpSocket.cs
- WeightedRandom.cs
- Utils.cs
- MethodSequenceListItem.cs
- PlayerDeathReason.cs
- Mount.cs
- Item.cs
- Main.cs

**Comment by hakusaro** [comment]
Is this done @WhiteXZ?
